### ISSUE TITLE
Error downloading modules

### ISSUE THREAD

**Issue by mabushey** [skyscrapers/terraform-neo4j#5]
$ terraform init 
```
Initializing modules...
- module.neo4j
  Getting source "github.com/skyscrapers/terraform-neo4j?ref=0.1"
Error downloading modules: Error loading modules: error downloading 'https://github.com/skyscrapers/terraform-neo4j.git?ref=0.1': /usr/bin/git exited with 1: error: pathspec '0.1' did not match any file(s) known to git.
```

Any ideas?

**Comment by mabushey** [comment]
I removed the `?ref=0.1` and now I get:
```
Initializing modules...
- module.neo4j
  Getting source "github.com/skyscrapers/terraform-neo4j"
- module.neo4j.core
  Getting source "github.com/skyscrapers/terraform-instances//instance?ref=2.0.14"
- module.neo4j.puppet_userdata
  Getting source "github.com/skyscrapers/terraform-instances//puppet-userdata?ref=2.1.0"

Error: module 'neo4j': unknown variable referenced: 'project'; define it with a 'variable' block



Error: module 'neo4j': unknown module referenced: vpc



Error: module 'neo4j': unknown module referenced: vpc



Error: module 'neo4j': unknown module referenced: sg_all



Error: module 'neo4j': unknown resource 'data.terraform_remote_state.static' referenced in variable data.terraform_remote_state.static.jumphost_sg_id



Error: module 'neo4j': unknown resource 'data.aws_security_group.kubernetes' referenced in variable data.aws_security_group.kubernetes.id



Error: module 'neo4j': reference to undefined module "sg_all"



Error: module 'neo4j': reference to undefined module "vpc"



Error: module 'neo4j': reference to undefined module "vpc"

```

**Comment by duboisph** [comment]
For the `?ref=`, you need to point it to a [correct release](https://github.com/skyscrapers/terraform-neo4j/releases). At this moment `0.9.5` is the latest.

As for the other errors: you shouldn't copy/paste the example, but set the parameters correctly for your own environment. What every parameter does is described in the README.

**Comment by duboisph** [comment]
That aside, this module is very specific to our own usage and will not work out-of-the box for you. It will not install neo4j either, as that's [handled by our puppetmaster](https://github.com/skyscrapers/terraform-neo4j/blob/master/main.tf#L42).

It's probably best that you create a fork if you want to use our module.

**Comment by mabushey** [comment]
Thank for the help! I provision infrastructure via Terraform, and configure with Ansible so that part fits my workflow perfectly. I'll dig through the code and figure out what's going on. I appreciate you posting this as it's exactly what I need to set up right now. Have a great day Philip. :)
